ALTER TYPE "WorkshopJobStatus" RENAME TO "WorkshopJobStatus_old";

CREATE TYPE "WorkshopJobStatus" AS ENUM (
  'BOOKED',
  'IN_PROGRESS',
  'WAITING_FOR_APPROVAL',
  'WAITING_FOR_PARTS',
  'ON_HOLD',
  'READY_FOR_COLLECTION',
  'COMPLETED',
  'CANCELLED'
);

ALTER TABLE "WorkshopJob"
ALTER COLUMN "status" DROP DEFAULT;

ALTER TABLE "WorkshopJob"
ALTER COLUMN "status" TYPE "WorkshopJobStatus"
USING (
  CASE "status"::text
    WHEN 'BOOKING_MADE' THEN 'BOOKED'
    WHEN 'BIKE_ARRIVED' THEN 'IN_PROGRESS'
    WHEN 'WAITING_FOR_APPROVAL' THEN 'WAITING_FOR_APPROVAL'
    WHEN 'APPROVED' THEN 'IN_PROGRESS'
    WHEN 'WAITING_FOR_PARTS' THEN 'WAITING_FOR_PARTS'
    WHEN 'ON_HOLD' THEN 'ON_HOLD'
    WHEN 'BIKE_READY' THEN 'READY_FOR_COLLECTION'
    WHEN 'COMPLETED' THEN 'COMPLETED'
    WHEN 'CANCELLED' THEN 'CANCELLED'
    ELSE 'BOOKED'
  END
)::"WorkshopJobStatus";

ALTER TABLE "WorkshopJob"
ALTER COLUMN "status" SET DEFAULT 'BOOKED';

DROP TYPE "WorkshopJobStatus_old";
