### Rota overview
GET http://localhost:3000/api/rota
X-Staff-Role: MANAGER
X-Staff-Id: rota-manager

### Save rota assignment
POST http://localhost:3000/api/rota/assignments
Content-Type: application/json
X-Staff-Role: MANAGER
X-Staff-Id: rota-manager

{
  "rotaPeriodId": "{{rotaPeriodId}}",
  "staffId": "rota-alex-id",
  "date": "2026-03-10",
  "shiftType": "FULL_DAY"
}

### Clear rota assignment
DELETE http://localhost:3000/api/rota/assignments/{{assignmentId}}
X-Staff-Role: MANAGER
X-Staff-Id: rota-manager

### Holiday requests list (mine)
GET http://localhost:3000/api/rota/holiday-requests?scope=mine
X-Staff-Role: STAFF
X-Staff-Id: rota-alex-id

### Holiday requests list (all)
GET http://localhost:3000/api/rota/holiday-requests?scope=all
X-Staff-Role: MANAGER
X-Staff-Id: rota-manager

### Submit holiday request
POST http://localhost:3000/api/rota/holiday-requests
Content-Type: application/json
X-Staff-Role: STAFF
X-Staff-Id: rota-alex-id

{
  "startDate": "2026-03-09",
  "endDate": "2026-03-15",
  "requestNotes": "Family trip"
}

### Approve holiday request
POST http://localhost:3000/api/rota/holiday-requests/{{holidayRequestId}}/approve
Content-Type: application/json
X-Staff-Role: MANAGER
X-Staff-Id: rota-manager

{}

### Reject holiday request
POST http://localhost:3000/api/rota/holiday-requests/{{holidayRequestId}}/reject
Content-Type: application/json
X-Staff-Role: ADMIN
X-Staff-Id: rota-admin

{}

### Cancel holiday request
POST http://localhost:3000/api/rota/holiday-requests/{{holidayRequestId}}/cancel
X-Staff-Role: STAFF
X-Staff-Id: rota-alex-id

### Rota import preview
POST http://localhost:3000/api/rota/import/preview
Content-Type: application/json
X-Staff-Role: ADMIN
X-Staff-Id: rota-admin

{
  "fileName": "rota-export.csv",
  "spreadsheetText": "Week commencing,09/03/2026,,,,,,\nName,Mon 09/03,Tue 10/03,Wed 11/03,Thu 12/03,Fri 13/03,Sat 14/03,Sun 15/03\nAlex Turner,10-6:30,10-6:30,Training day,x,,9-4:30,\nJordan Patel,,10-6:30,,10-6:30,10-6:30,x,"
}

### Rota import confirm
POST http://localhost:3000/api/rota/import/confirm
Content-Type: application/json
X-Staff-Role: ADMIN
X-Staff-Id: rota-admin

{
  "fileName": "rota-export.csv",
  "previewKey": "replace-with-preview-key",
  "spreadsheetText": "Week commencing,09/03/2026,,,,,,\nName,Mon 09/03,Tue 10/03,Wed 11/03,Thu 12/03,Fri 13/03,Sat 14/03,Sun 15/03\nAlex Turner,10-6:30,10-6:30,Training day,x,,9-4:30,\nJordan Patel,,10-6:30,,10-6:30,10-6:30,x,"
}
