const file = (path, label) => ({ type: "fileExists", path, label });
const text = (path, match, label) => ({ type: "text", path, match, label });
const script = (name, label) => ({ type: "packageScript", script: name, label });
const model = (name, label) => ({ type: "schemaModel", model: name, label });

module.exports = {
  version: 1,
  sourceDoc: "docs/ROADMAP.md",
  loc: {
    roots: ["src", "frontend/src", "scripts", "e2e", "prisma"],
    extensions: [".ts", ".tsx", ".js", ".jsx", ".prisma", ".sql", ".css"],
    excludeDirectories: [
      "node_modules",
      "dist",
      "frontend/dist",
      "coverage",
      "playwright-report",
      "test-results",
      ".git",
      "tmp",
    ],
  },
  phases: [
    {
      id: "phase1",
      name: "Phase 1 — POS & Cash Control",
      items: [
        {
          id: "pos-sale-workflow",
          label: "POS sale workflow and basket handling",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("frontend/src/pages/PosPage.tsx", "React POS screen exists"),
            text("frontend/src/App.tsx", 'path="/pos"', "POS route is mounted"),
            file("scripts/pos_m28_smoke_tests.js", "POS smoke coverage exists"),
            text("e2e/critical/critical-smoke.spec.js", "POS add to basket, checkout cash", "Playwright checkout flow exists"),
          ],
        },
        {
          id: "payments-and-tenders",
          label: "Payment intents and mixed tender handling",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            model("SaleTender", "Sale tender model exists"),
            file("scripts/payments_m31_smoke_tests.js", "Payment intent smoke exists"),
            file("scripts/pos_tenders_m39_smoke_tests.js", "Split tender smoke exists"),
            file("src/services/salesService.ts", "Sales service exists"),
          ],
        },
        {
          id: "receipts-and-refunds",
          label: "Receipts and refunds",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            model("Receipt", "Receipt model exists"),
            model("Refund", "Refund model exists"),
            file("scripts/receipts_m40_smoke_tests.js", "Receipt smoke exists"),
            file("scripts/refunds_m41_smoke_tests.js", "Refund smoke exists"),
          ],
        },
        {
          id: "cash-control",
          label: "Till sessions and cash management",
          weight: 2,
          partialAt: 2,
          completeAt: 5,
          signals: [
            model("CashSession", "Cash session model exists"),
            model("CashMovement", "Cash movement model exists"),
            file("src/services/managementCashService.ts", "Cash management service exists"),
            file("scripts/till_m37_smoke_tests.js", "Till smoke exists"),
            file("scripts/cash_m42_smoke_tests.js", "Cash management smoke exists"),
          ],
        },
      ],
    },
    {
      id: "phase2",
      name: "Phase 2 — Product Catalogue",
      items: [
        {
          id: "catalogue-data-model",
          label: "Product and variant catalogue model",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            model("Product", "Product model exists"),
            model("Variant", "Variant model exists"),
            file("src/services/productService.ts", "Product service exists"),
            file("scripts/catalog_m25_smoke_tests.js", "Catalogue smoke exists"),
          ],
        },
        {
          id: "catalogue-management-surface",
          label: "Product management and search surfaces",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("frontend/src/pages/InventoryPage.tsx", "Inventory page exists"),
            text("frontend/src/App.tsx", 'path="/inventory/products"', "Product list route exists"),
            file("frontend/src/pages/ProductDataQueuePage.tsx", "Product data queue exists"),
            file("scripts/products_m29_smoke_tests.js", "Products smoke exists"),
          ],
        },
        {
          id: "barcode-sku-pricing",
          label: "Barcode, SKU, and pricing support",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            text("prisma/schema.prisma", "sku              String  @unique", "Unique SKU is modeled"),
            text("prisma/schema.prisma", "barcode          String? @unique", "Unique barcode is modeled"),
            text("frontend/src/pages/PosPage.tsx", "barcode or SKU", "POS scanner/search messaging exists"),
            text("src/services/productService.ts", "VARIANT_EXISTS", "Product service enforces SKU/barcode uniqueness"),
          ],
        },
        {
          id: "taxonomy-and-attributes",
          label: "Categories, brands, attributes, and pricing review",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            text("prisma/schema.prisma", "category    String?", "Product category field exists"),
            text("prisma/schema.prisma", "brand       String?", "Product brand field exists"),
            text("frontend/src/navigation/navigationConfig.ts", 'to: "/inventory/products/categories"', "Category route is present"),
            file("scripts/pricing_exceptions_m122_smoke_tests.js", "Pricing exceptions smoke exists"),
          ],
        },
      ],
    },
    {
      id: "phase3",
      name: "Phase 3 — Inventory Control",
      items: [
        {
          id: "stock-ledger-foundation",
          label: "Stock ledger and on-hand inventory",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            model("StockLedgerEntry", "Stock ledger model exists"),
            file("src/services/inventoryLedgerService.ts", "Inventory ledger service exists"),
            file("src/services/stockService.ts", "Stock service exists"),
            file("scripts/inventory_m24_smoke_tests.js", "Inventory ledger smoke exists"),
          ],
        },
        {
          id: "adjustments-and-movements",
          label: "Stock adjustments and movement history",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("src/controllers/inventoryAdjustmentController.ts", "Inventory adjustment controller exists"),
            file("src/routes/inventoryLedgerRoutes.ts", "Inventory ledger routes exist"),
            file("scripts/inventory_adjust_m33_smoke_tests.js", "Inventory adjustment smoke exists"),
            text("frontend/src/App.tsx", 'path="/inventory/adjustments"', "Inventory adjustments route exists"),
          ],
        },
        {
          id: "multi-location-stock",
          label: "Location-aware stock records and views",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            model("StockLocation", "Stock location model exists"),
            file("frontend/src/pages/InventoryLocationsPage.tsx", "Inventory locations page exists"),
            script("test:m118", "Inventory locations smoke script is registered"),
            file("scripts/inventory_locations_m118_smoke_tests.js", "Inventory locations smoke exists"),
          ],
        },
        {
          id: "transfers-and-replenishment",
          label: "Transfers and replenishment insight",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("src/services/stockTransferService.ts", "Stock transfer service exists"),
            file("frontend/src/pages/TransferQueuePage.tsx", "Transfer queue page exists"),
            file("scripts/stock_transfers_smoke_tests.js", "Stock transfer smoke exists"),
            file("scripts/reorder_suggestions_m119_smoke_tests.js", "Reorder suggestion smoke exists"),
          ],
        },
      ],
    },
    {
      id: "phase4",
      name: "Phase 4 — Stock Take",
      items: [
        {
          id: "stocktake-session-lifecycle",
          label: "Stocktake session lifecycle",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("src/services/stocktakeService.ts", "Stocktake service exists"),
            file("frontend/src/pages/InventoryStocktakesPage.tsx", "Stocktake page exists"),
            file("scripts/stocktake_m18_smoke_tests.js", "Foundational stocktake smoke exists"),
            file("scripts/stocktake_m26_smoke_tests.js", "Stocktake workflow smoke exists"),
          ],
        },
        {
          id: "scan-and-bulk-counting",
          label: "Scan-first and bulk counting workflow",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            text("frontend/src/pages/InventoryStocktakesPage.tsx", "stocktake-scan-code", "Scan mode controls exist"),
            text("frontend/src/pages/InventoryStocktakesPage.tsx", "stocktake-bulk-import", "Bulk import controls exist"),
            text("frontend/src/pages/InventoryStocktakesPage.tsx", "Count Scan", "Stocktake scan action exists"),
            text("e2e/inventory/stocktake.spec.js", "Stocktake scan mode and bulk import", "Playwright stocktake scan coverage exists"),
          ],
        },
        {
          id: "variance-review-and-finalize",
          label: "Variance review and controlled finalization",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            text("frontend/src/pages/InventoryStocktakesPage.tsx", "/review", "Stocktake review request exists"),
            text("frontend/src/pages/InventoryStocktakesPage.tsx", "/finalize", "Stocktake finalize request exists"),
            text("frontend/src/pages/InventoryStocktakesPage.tsx", "varianceQty", "Variance display exists"),
            text("src/services/stocktakeService.ts", "buildOnHandPreviewMapTx", "Expected-vs-counted preview logic exists"),
          ],
        },
        {
          id: "location-aware-stocktakes",
          label: "Location-aware count sessions",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            text("src/services/stocktakeService.ts", "locationId", "Stocktake service handles location ids"),
            text("src/services/stocktakeService.ts", "stocktake.location.name", "Stocktake detail includes location summary"),
            text("frontend/src/pages/InventoryStocktakesPage.tsx", "locationId", "Stocktake UI tracks locations"),
            file("frontend/src/pages/InventoryLocationsPage.tsx", "Inventory location page exists"),
          ],
        },
      ],
    },
    {
      id: "phase5",
      name: "Phase 5 — Purchasing",
      items: [
        {
          id: "suppliers-and-po",
          label: "Suppliers and purchase orders",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            model("Supplier", "Supplier model exists"),
            model("PurchaseOrder", "Purchase order model exists"),
            file("frontend/src/pages/SuppliersPage.tsx", "Suppliers page exists"),
            file("scripts/purchasing_m17_smoke_tests.js", "Purchasing foundation smoke exists"),
          ],
        },
        {
          id: "receiving-workflow",
          label: "Receiving and delivery handling",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("frontend/src/pages/SupplierReceivingPage.tsx", "Supplier receiving page exists"),
            text("frontend/src/App.tsx", 'path="/purchasing/receive-deliveries"', "Receive deliveries route exists"),
            file("scripts/purchase_orders_m27_smoke_tests.js", "Purchase order workflow smoke exists"),
            text("src/services/purchasingService.ts", "receivePurchaseOrder", "Purchase receiving service exists"),
          ],
        },
        {
          id: "supplier-product-linking",
          label: "Supplier product linking and preferred costs",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            model("SupplierProductLink", "Supplier product link model exists"),
            file("src/services/supplierProductLinkService.ts", "Supplier product link service exists"),
            file("scripts/supplier_product_links_smoke_tests.js", "Supplier product link smoke exists"),
            file("frontend/src/pages/SupplierCataloguePage.tsx", "Supplier catalogue page exists"),
          ],
        },
        {
          id: "purchasing-insight",
          label: "Purchasing performance and oversight",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("frontend/src/pages/PurchasingPage.tsx", "Purchasing page exists"),
            file("frontend/src/pages/SupplierPerformancePage.tsx", "Supplier performance page exists"),
            file("scripts/supplier_performance_m121_smoke_tests.js", "Supplier performance smoke exists"),
            text("frontend/src/App.tsx", 'path="/reports/inventory"', "Reporting routes are mounted"),
          ],
        },
      ],
    },
    {
      id: "phase6",
      name: "Phase 6 — Data Import / Export",
      items: [
        {
          id: "report-and-data-exports",
          label: "Operational exports and report downloads",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("frontend/src/pages/ExportHubPage.tsx", "Export hub page exists"),
            file("scripts/reports_csv_m22_smoke_tests.js", "CSV export smoke exists"),
            text("frontend/src/App.tsx", 'path="/management/exports"', "Export management route exists"),
            file("requests/reports.http", "Report request examples exist"),
          ],
        },
        {
          id: "csv-import-preview-confirm",
          label: "CSV import preview and confirm",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("src/services/productImportService.ts", "Product import service exists"),
            file("scripts/product_csv_import_smoke_tests.js", "Product import smoke exists"),
            file("frontend/src/pages/ProductDataQueuePage.tsx", "Product data queue page exists"),
            file("requests/product_import.http", "Product import request examples exist"),
          ],
        },
        {
          id: "backup-and-export-toolkit",
          label: "Backup and export toolkit",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("frontend/src/pages/BackupToolkitPage.tsx", "Backup toolkit page exists"),
            file("scripts/backup_database.sh", "Database backup helper exists"),
            file("scripts/upgrade_corepos.sh", "Upgrade helper exists"),
            file("docs/production_setup.md", "Production setup runbook exists"),
          ],
        },
        {
          id: "operational-upload-flows",
          label: "Operational import/upload helpers",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("frontend/src/pages/CashReceiptUploadPage.tsx", "Cash receipt upload page exists"),
            file("src/routes/publicReceiptUploadRoutes.ts", "Public receipt upload routes exist"),
            text("frontend/src/App.tsx", 'path="/receipt-upload/:token"', "Receipt upload route is mounted"),
            model("CashReceiptUploadToken", "Cash receipt upload token model exists"),
          ],
        },
      ],
    },
    {
      id: "phase7",
      name: "Phase 7 — Supplier Integrations",
      items: [
        {
          id: "supplier-catalogue-intake",
          label: "Supplier catalogue intake workspace",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("frontend/src/pages/SupplierCataloguePage.tsx", "Supplier catalogue page exists"),
            text("frontend/src/App.tsx", 'path="/management/catalogue"', "Catalogue management route exists"),
            file("src/services/supplierProductLinkService.ts", "Supplier link service exists"),
            file("requests/supplier_product_links.http", "Supplier product link request examples exist"),
          ],
        },
        {
          id: "supplier-link-groundwork",
          label: "Supplier-product linking groundwork",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            model("SupplierProductLink", "Supplier product link model exists"),
            file("src/routes/supplierProductLinkRoutes.ts", "Supplier product link routes exist"),
            file("scripts/supplier_product_links_smoke_tests.js", "Supplier link smoke exists"),
            file("src/services/purchasingService.ts", "Purchasing service exists"),
          ],
        },
        {
          id: "supplier-feed-automation",
          label: "Automated supplier feed ingestion",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("src/services/supplierFeedService.ts", "Supplier feed service exists"),
            file("src/routes/supplierFeedRoutes.ts", "Supplier feed routes exist"),
            file("frontend/src/pages/SupplierFeedPage.tsx", "Supplier feed page exists"),
            file("scripts/supplier_feed_smoke_tests.js", "Supplier feed smoke exists"),
          ],
        },
        {
          id: "supplier-availability-sync",
          label: "Automated supplier stock and cost sync",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("src/services/supplierAvailabilityService.ts", "Supplier availability service exists"),
            file("src/services/supplierPricingSyncService.ts", "Supplier pricing sync service exists"),
            file("frontend/src/pages/SupplierAvailabilityPage.tsx", "Supplier availability page exists"),
            file("scripts/supplier_availability_smoke_tests.js", "Supplier availability smoke exists"),
          ],
        },
      ],
    },
    {
      id: "phase8",
      name: "Phase 8 — Workshop System",
      items: [
        {
          id: "workshop-job-board",
          label: "Workshop queue and job lifecycle",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            model("WorkshopJob", "Workshop job model exists"),
            file("frontend/src/pages/WorkshopPage.tsx", "Workshop page exists"),
            file("frontend/src/pages/WorkshopJobPage.tsx", "Workshop job page exists"),
            file("scripts/workshop_m30_smoke_tests.js", "Workshop lifecycle smoke exists"),
          ],
        },
        {
          id: "intake-booking-collection",
          label: "Check-in, bookings, and collection workflow",
          weight: 3,
          partialAt: 2,
          completeAt: 5,
          signals: [
            file("frontend/src/pages/WorkshopCheckInPage.tsx", "Workshop check-in page exists"),
            file("frontend/src/pages/WorkshopBookingsPage.tsx", "Workshop bookings page exists"),
            file("frontend/src/pages/WorkshopCollectionPage.tsx", "Workshop collection page exists"),
            file("scripts/workshop_checkout_deposit_tests.js", "Workshop deposit/checkout smoke exists"),
            file("scripts/workshop_m12_smoke_tests.js", "Workshop booking management smoke exists"),
          ],
        },
        {
          id: "parts-labour-and-stock-linkage",
          label: "Parts, labour, and stock linkage",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            model("WorkshopJobPart", "Workshop job part model exists"),
            model("WorkshopJobLine", "Workshop job line model exists"),
            file("src/services/workshopPartService.ts", "Workshop part service exists"),
            text("src/services/workshopService.ts", "inventoryMovement", "Workshop service writes inventory movement history"),
          ],
        },
        {
          id: "workshop-analytics-and-followup",
          label: "Analytics, reminders, and workshop support surfaces",
          weight: 2,
          partialAt: 2,
          completeAt: 5,
          signals: [
            file("frontend/src/pages/WorkshopPerformancePage.tsx", "Workshop performance page exists"),
            file("frontend/src/pages/WorkshopCapacityPage.tsx", "Workshop capacity page exists"),
            file("frontend/src/pages/WorkshopAgeingPage.tsx", "Workshop ageing page exists"),
            file("frontend/src/pages/WorkshopPrintCentrePage.tsx", "Workshop print centre exists"),
            file("scripts/workshop_capacity_m123_smoke_tests.js", "Workshop capacity smoke exists"),
          ],
        },
      ],
    },
    {
      id: "phase9",
      name: "Phase 9 — Staff & Operations",
      items: [
        {
          id: "roles-auth-and-pin",
          label: "Role-based auth and PIN login",
          weight: 3,
          partialAt: 2,
          completeAt: 5,
          signals: [
            file("src/services/authService.ts", "Auth service exists"),
            file("scripts/auth_m35_smoke_tests.js", "Auth smoke exists"),
            file("scripts/admin_m36_smoke_tests.js", "Admin smoke exists"),
            file("scripts/pin_auth_foundation_smoke_tests.js", "PIN auth smoke exists"),
            file("frontend/src/pages/PinSettingsPage.tsx", "PIN settings page exists"),
          ],
        },
        {
          id: "management-dashboard-and-reports",
          label: "Management dashboard and reporting surfaces",
          weight: 3,
          partialAt: 2,
          completeAt: 5,
          signals: [
            file("frontend/src/pages/ManagementDashboardPage.tsx", "Management dashboard exists"),
            file("frontend/src/pages/SalesAnalyticsPage.tsx", "Sales analytics exists"),
            file("frontend/src/pages/StaffPerformancePage.tsx", "Staff performance page exists"),
            file("scripts/action_centre_m126_smoke_tests.js", "Action centre smoke exists"),
            file("scripts/health_monitoring_smoke_tests.js", "Health monitoring smoke exists"),
          ],
        },
        {
          id: "activity-audit-and-diagnostics",
          label: "Activity, audit, backups, and diagnostics",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("frontend/src/pages/ActivityPage.tsx", "Activity page exists"),
            file("frontend/src/pages/OpsHealthPage.tsx", "Ops health page exists"),
            file("frontend/src/pages/BackupToolkitPage.tsx", "Backup toolkit exists"),
            text("prisma/schema.prisma", "model AuditLog", "Audit log model exists"),
          ],
        },
        {
          id: "planning-capacity-and-rota",
          label: "Capacity, calendar, and rota planning",
          weight: 2,
          partialAt: 2,
          completeAt: 4,
          signals: [
            file("frontend/src/pages/WorkshopCalendarPage.tsx", "Workshop calendar exists"),
            file("frontend/src/pages/DashboardSettingsPage.tsx", "Dashboard settings exists"),
            text("frontend/src/navigation/navigationConfig.ts", 'to: "/settings/staff-rota"', "Staff rota route exists"),
            file("scripts/workshop_capacity_m123_smoke_tests.js", "Capacity smoke exists"),
          ],
        },
      ],
    },
    {
      id: "phase10",
      name: "Phase 10 — Rental Services",
      items: [
        {
          id: "hire-assets-and-bookings",
          label: "Hire assets and booking foundation",
          weight: 3,
          partialAt: 2,
          completeAt: 4,
          signals: [
            text("prisma/schema.prisma", "model HireAsset", "Hire asset model exists"),
            text("prisma/schema.prisma", "model HireBooking", "Hire booking model exists"),
            file("src/services/bikeHireService.ts", "Bike hire service exists"),
            file("scripts/bike_hire_foundation_smoke_tests.js", "Bike hire smoke exists"),
          ],
        },
        {
          id: "rental-desk-ui",
          label: "Rental desk UI and routes",
          weight: 2,
          partialAt: 3,
          completeAt: 5,
          signals: [
            file("frontend/src/pages/BikeHirePage.tsx", "Bike hire page exists"),
            text("frontend/src/App.tsx", 'path="/rental/calendar"', "Rental calendar route exists"),
            text("frontend/src/App.tsx", 'path="/rental/returns"', "Rental returns route exists"),
            text("frontend/src/navigation/navigationConfig.ts", 'to: "/rental/history"', "Rental navigation exists"),
            file("frontend/src/pages/RentalCalendarPage.tsx", "Dedicated rental calendar page exists"),
          ],
        },
        {
          id: "deposit-and-return-lifecycle",
          label: "Deposits, checkout, return, and cancellation",
          weight: 1,
          partialAt: 2,
          completeAt: 4,
          signals: [
            text("src/services/bikeHireService.ts", "depositHeldPence", "Hire deposit handling exists"),
            text("src/services/bikeHireService.ts", 'depositOutcome?: "RETURNED" | "KEPT"', "Deposit return/keep handling exists"),
            text("frontend/src/pages/BikeHirePage.tsx", "Deposit {formatStatus(booking.depositStatus)}", "Deposit state is displayed in UI"),
            text("scripts/bike_hire_foundation_smoke_tests.js", "hire returns and cancellations restore asset availability", "Return/cancel coverage exists"),
          ],
        },
        {
          id: "rental-calendar-depth",
          label: "Calendar, agreements, and damage depth",
          weight: 6,
          partialAt: 3,
          completeAt: 5,
          signals: [
            text("frontend/src/App.tsx", 'path="/rental/calendar"', "Rental calendar route exists"),
            text("frontend/src/pages/BikeHirePage.tsx", "condition note", "Condition notes exist"),
            file("src/services/hireAgreementService.ts", "Hire agreement service exists"),
            file("src/services/hireDamageService.ts", "Hire damage service exists"),
            file("scripts/rental_calendar_smoke_tests.js", "Rental calendar smoke exists"),
          ],
        },
      ],
    },
    {
      id: "phase11",
      name: "Phase 11 — Online Store & Website Builder",
      items: [
        {
          id: "customer-site-foundation",
          label: "Customer-facing site foundation",
          weight: 2,
          partialAt: 2,
          completeAt: 5,
          signals: [
            file("frontend/src/pages/CustomerSitePage.tsx", "Customer site page exists"),
            text("frontend/src/App.tsx", 'path="/site"', "Public site home route exists"),
            text("frontend/src/App.tsx", 'path="/site/services"', "Public site services route exists"),
            text("frontend/src/App.tsx", 'path="/site/contact"', "Public site contact route exists"),
            text("frontend/src/App.tsx", 'path="/site/workshop"', "Public site workshop route exists"),
          ],
        },
        {
          id: "online-store-scaffolding",
          label: "Online store route and navigation scaffolding",
          weight: 2,
          partialAt: 3,
          completeAt: 5,
          signals: [
            text("frontend/src/navigation/navigationConfig.ts", 'to: "/online-store/orders"', "Online store nav entry exists"),
            text("frontend/src/App.tsx", 'path="/online-store/orders"', "Online store orders route exists"),
            text("frontend/src/App.tsx", 'path="/online-store/products"', "Online store products route exists"),
            text("frontend/src/App.tsx", 'path="/online-store/website-builder"', "Website builder route exists"),
            file("frontend/src/pages/OnlineStoreOrdersPage.tsx", "Dedicated online store orders page exists"),
          ],
        },
        {
          id: "orders-and-click-collect",
          label: "Orders and click & collect workflow depth",
          weight: 4,
          partialAt: 3,
          completeAt: 6,
          signals: [
            text("frontend/src/App.tsx", 'path="/online-store/orders"', "Online store orders route exists"),
            text("frontend/src/App.tsx", 'path="/online-store/click-collect"', "Click & collect route exists"),
            file("src/routes/onlineStoreRoutes.ts", "Online store routes exist"),
            file("src/services/orderService.ts", "Order service exists"),
            file("scripts/online_store_smoke_tests.js", "Online store smoke exists"),
            file("requests/online_store.http", "Online store request examples exist"),
          ],
        },
        {
          id: "website-builder-depth",
          label: "Website builder and content editing depth",
          weight: 4,
          partialAt: 3,
          completeAt: 6,
          signals: [
            text("frontend/src/App.tsx", 'path="/online-store/website-builder"', "Website builder route exists"),
            file("frontend/src/pages/WebsiteBuilderPage.tsx", "Website builder page exists"),
            file("src/services/siteBuilderService.ts", "Site builder service exists"),
            file("scripts/site_builder_smoke_tests.js", "Site builder smoke exists"),
            file("src/routes/siteBuilderRoutes.ts", "Site builder routes exist"),
            file("frontend/src/pages/MediaLibraryPage.tsx", "Media library page exists"),
          ],
        },
      ],
    },
  ],
};
