name: Deploy to CorePOS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy CorePOS
        shell: cmd
        run: |
          C:\Users\coreposadmin\corepos-runtime\deploy-corepos.cmd